import type { Workout } from "./workout";

export const FALLBACK_WORKOUTS: Workout[] = [
  {
    id: 1,
    name: "Barbell Bench Press",
    image: "https://img.magnific.com/free-photo/portrait-anime-character-doing-fitness-exercising_23-2151666664.jpg?w=740",
    muscleGroups: ["Chest", "Arms"],
    equipment: "Barbell, Bench",
    difficulty: "Intermediate",
    duration: 25,
    caloriesBurned: 180,
    sets: 4,
    reps: "6-8",
    rating: 4.8,
    description: "A compound press that builds chest thickness, triceps, and pressing power from a stable bench.",
    instructions: [
      "Lie on the bench with eyes under the bar and feet planted.",
      "Unrack with locked elbows and lower the bar to mid-chest.",
      "Press up in a slight arc until elbows lock without bouncing.",
      "Keep shoulder blades pinched and a natural arch in the back.",
    ],
  },
  {
    id: 2,
    name: "Pull-Up",
    image: "https://img.magnific.com/free-photo/portrait-anime-character-doing-fitness-exercising_23-2151666664.jpg?w=740",
    muscleGroups: ["Back", "Arms"],
    equipment: "Pull-up Bar",
    difficulty: "Intermediate",
    duration: 15,
    caloriesBurned: 120,
    sets: 3,
    reps: "8-10",
    rating: 4.7,
    description: "An upper-body pulling exercise that builds lats, upper back thickness, and bicep strength.",
    instructions: [
      "Grip the pull-up bar with hands slightly wider than shoulder-width.",
      "Engage your core and pull your chest up towards the bar.",
      "Pause briefly when chin clears the bar.",
      "Lower under control back to a full dead-hang position.",
    ],
  },
  {
    id: 3,
    name: "Back Squat",
    image: "https://img.magnific.com/free-photo/portrait-anime-character-doing-fitness-exercising_23-2151666664.jpg?w=740",
    muscleGroups: ["Legs", "Core"],
    equipment: "Barbell, Rack",
    difficulty: "Advanced",
    duration: 30,
    caloriesBurned: 240,
    sets: 5,
    reps: "5",
    rating: 4.9,
    description: "The king of lower body movements developing quadriceps, glutes, hamstrings, and core bracing.",
    instructions: [
      "Step under the bar resting it across the upper traps.",
      "Unrack, take two steps back, and establish shoulder-width stance.",
      "Break at hips and knees simultaneously to sit below parallel.",
      "Drive powerfully through midfoot back to standing position.",
    ],
  },
  {
    id: 4,
    name: "Overhead Press",
    image: "https://img.magnific.com/free-photo/portrait-anime-character-doing-fitness-exercising_23-2151666664.jpg?w=740",
    muscleGroups: ["Shoulders", "Arms"],
    equipment: "Barbell",
    difficulty: "Intermediate",
    duration: 20,
    caloriesBurned: 150,
    sets: 4,
    reps: "6-8",
    rating: 4.6,
    description: "A strict vertical press developing full deltoid strength, triceps lock, and overhead stability.",
    instructions: [
      "Stand with feet shoulder-width and grip bar at collarbone height.",
      "Brace core and squeeze glutes before pressing vertically.",
      "Press bar overhead in a straight line past your face.",
      "Lock out elbows overhead and return bar under control.",
    ],
  },
  {
    id: 5,
    name: "Dumbbell Bicep Curl",
    image: "https://img.magnific.com/free-photo/portrait-anime-character-doing-fitness-exercising_23-2151666664.jpg?w=740",
    muscleGroups: ["Arms"],
    equipment: "Dumbbells",
    difficulty: "Beginner",
    duration: 12,
    caloriesBurned: 80,
    sets: 3,
    reps: "10-12",
    rating: 4.5,
    description: "An isolation movement targeting both heads of the biceps for peaked arm strength and hypertrophy.",
    instructions: [
      "Stand upright holding a dumbbell in each hand at arms length.",
      "Keep elbows tucked close to your torso.",
      "Curl the weights upward while contracting your biceps.",
      "Slowly lower dumbbells back to starting position.",
    ],
  },
  {
    id: 6,
    name: "Dumbbell Bicep Curl",
    image: "https://img.magnific.com/free-photo/portrait-anime-character-doing-fitness-exercising_23-2151666664.jpg?w=740",
    muscleGroups: ["Arms"],
    equipment: "Dumbbells",
    difficulty: "Beginner",
    duration: 12,
    caloriesBurned: 80,
    sets: 3,
    reps: "10-12",
    rating: 4.5,
    description: "An isolation movement targeting both heads of the biceps for peaked arm strength and hypertrophy.",
    instructions: [
      "Stand upright holding a dumbbell in each hand at arms length.",
      "Keep elbows tucked close to your torso.",
      "Curl the weights upward while contracting your biceps.",
      "Slowly lower dumbbells back to starting position.",
    ],
  },
  {
    id: 7,
    name: "Hollow-Body Plank",
    image: "https://img.magnific.com/free-photo/portrait-anime-character-doing-fitness-exercising_23-2151666664.jpg?w=740",
    muscleGroups: ["Core"],
    equipment: "Bodyweight",
    difficulty: "Beginner",
    duration: 10,
    caloriesBurned: 60,
    sets: 3,
    reps: "45-60s",
    rating: 4.4,
    description: "An isometric core exercise promoting anti-extension strength and pelvic control.",
    instructions: [
      "Lie face down and prop yourself onto forearms and toes.",
      "Tuck your pelvis and brace abs as if preparing for impact.",
      "Maintain a flat spine without letting lower back sag.",
      "Breathe rhythmically while holding tension throughout the body.",
    ],
  },
  {
    id: 8,
    name: "Dumbbell Bicep Curl",
    image: "https://img.magnific.com/free-photo/portrait-anime-character-doing-fitness-exercising_23-2151666664.jpg?w=740",
    muscleGroups: ["Arms"],
    equipment: "Dumbbells",
    difficulty: "Beginner",
    duration: 12,
    caloriesBurned: 80,
    sets: 3,
    reps: "10-12",
    rating: 4.5,
    description: "An isolation movement targeting both heads of the biceps for peaked arm strength and hypertrophy.",
    instructions: [
      "Stand upright holding a dumbbell in each hand at arms length.",
      "Keep elbows tucked close to your torso.",
      "Curl the weights upward while contracting your biceps.",
      "Slowly lower dumbbells back to starting position.",
    ],
  },
  {
    id: 9,
    name: "Conventional Deadlift",
    image: "https://img.magnific.com/free-photo/portrait-anime-character-doing-fitness-exercising_23-2151666664.jpg?w=740",
    muscleGroups: ["Back", "Legs"],
    equipment: "Barbell",
    difficulty: "Advanced",
    duration: 28,
    caloriesBurned: 200,
    sets: 4,
    reps: "5",
    rating: 4.9,
    description: "A premier posterior chain compound lift working erectors, glutes, hamstrings, and grip.",
    instructions: [
      "Stand with feet hip-width with barbell positioned over midfoot.",
      "Hinge at hips and grip the bar just outside your knees.",
      "Flatten back, pull slack out of the bar, and drive floor away.",
      "Lock hips out at top and return bar under strict control.",
    ],
  },
  {
    id: 10,
    name: "Push-Up",
    image: "https://img.magnific.com/free-photo/portrait-anime-character-doing-fitness-exercising_23-2151666664.jpg?w=740",
    muscleGroups: ["Chest", "Arms", "Core"],
    equipment: "Bodyweight",
    difficulty: "Beginner",
    duration: 10,
    caloriesBurned: 80,
    sets: 3,
    reps: "15-20",
    rating: 4.5,
    description: "A fundamental calisthenic pressing exercise for chest, anterior delts, and core stability.",
    instructions: [
      "Place hands slightly wider than shoulders in high plank position.",
      "Lower chest towards floor while keeping elbows at 45 degrees.",
      "Touch chest lightly to the ground without arching back.",
      "Push the floor away to return to top locked position.",
    ],
  },
  {
    id: 11,
    name: "Walking Lunge",
    image: "https://img.magnific.com/free-photo/portrait-anime-character-doing-fitness-exercising_23-2151666664.jpg?w=740",
    muscleGroups: ["Legs"],
    equipment: "Dumbbells (optional)",
    difficulty: "Intermediate",
    duration: 15,
    caloriesBurned: 110,
    sets: 3,
    reps: "12 per leg",
    rating: 4.6,
    description: "A unilateral leg builder enhancing quad and glute strength while testing balance and coordination.",
    instructions: [
      "Stand tall holding dumbbells at sides or using bodyweight.",
      "Take a controlled step forward and lower back knee towards ground.",
      "Push through front heel to step up into next stride.",
      "Maintain an upright torso and steady pacing throughout.",
    ],
  },
  {
    id: 12,
    name: "Russian Twist",
    image: "https://img.magnific.com/free-photo/portrait-anime-character-doing-fitness-exercising_23-2151666664.jpg?w=740",
    muscleGroups: ["Core"],
    equipment: "Medicine Ball",
    difficulty: "Beginner",
    duration: 8,
    caloriesBurned: 70,
    sets: 3,
    reps: "20 total",
    rating: 4.1,
    description: "A rotational core exercise targeting the internal and external obliques and deep transverse abdominis.",
    instructions: [
      "Sit on floor with knees bent and feet elevated slightly.",
      "Lean torso back slightly to create a V-shape with thighs.",
      "Hold medicine ball with both hands and rotate torso side to side.",
      "Touch ball lightly to floor on each side under steady control.",
    ],
  },
];
